/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Clases.Categoria;
import Clases.Dispositivo;
import Clases.Lugar;
import Clases.Usuario;
import Controladores.Fabrica;
import Controladores.IControlador;
import static Swing.Console.EscritorioMenu;
import java.io.File;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JFileChooser;

/**
 *
 * @author Nelson
 */
public class AltaEquipo2 extends javax.swing.JInternalFrame {
    private Categoria cate;
    private IControlador IC; 
    private File f;
    private Dispositivo dis;
    
    /**
     * Creates new form AltaEquipo2
     */
    public AltaEquipo2(Dispositivo disp) {
        initComponents();
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        IC = fabrica.getICtrl();
        this.cate=disp.getTipo();
        this.dis=disp;
        controlOcultos();
        CargarComboLugar();
        CargarComboUsuarios();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jBnuevoUsu = new javax.swing.JButton();
        jBnuevaUbic = new javax.swing.JButton();
        jCBUsuario = new javax.swing.JComboBox();
        jCBUbicacion = new javax.swing.JComboBox();
        jLUsuario = new javax.swing.JLabel();
        jTIP = new javax.swing.JTextField();
        jLIP = new javax.swing.JLabel();
        jLXML = new javax.swing.JLabel();
        jBExaminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTObserva = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jBFinalizar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBActualizarUsu = new javax.swing.JButton();
        jBActualizarUbi = new javax.swing.JButton();

        setClosable(true);

        jLabel6.setText("Ubicación:");

        jBnuevoUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevoU.png"))); // NOI18N
        jBnuevoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoUsuActionPerformed(evt);
            }
        });

        jBnuevaUbic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ubicacion.png"))); // NOI18N
        jBnuevaUbic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevaUbicActionPerformed(evt);
            }
        });

        jLUsuario.setText("Usuario:");

        jLIP.setText("IP:");

        jLXML.setText("Adjuntar XML");

        jBExaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar .png"))); // NOI18N
        jBExaminar.setText("Examinar");
        jBExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExaminarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTObserva);

        jLabel1.setText(" Observación:");

        jBFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finalizar.png"))); // NOI18N
        jBFinalizar.setText("Finalizar");
        jBFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarActionPerformed(evt);
            }
        });

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBActualizarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        jBActualizarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarUsuActionPerformed(evt);
            }
        });

        jBActualizarUbi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        jBActualizarUbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarUbiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBFinalizar)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLUsuario)
                            .addComponent(jLabel6)
                            .addComponent(jLIP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jTIP)
                                .addGap(33, 33, 33))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jCBUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBActualizarUbi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jCBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jBActualizarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBnuevoUsu)
                            .addComponent(jBnuevaUbic)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLXML)
                        .addGap(18, 18, 18)
                        .addComponent(jBExaminar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUsuario)
                    .addComponent(jCBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnuevoUsu)
                    .addComponent(jBActualizarUsu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCBUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnuevaUbic)
                    .addComponent(jBActualizarUbi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIP)
                    .addComponent(jTIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLXML)
                    .addComponent(jBExaminar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBFinalizar)
                    .addComponent(jBCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnuevoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoUsuActionPerformed
        // TODO add your handling code here:
        AltaUsuario au = new AltaUsuario();
        EscritorioMenu.add(au);
        au.show();
        this.jCBUsuario.removeAllItems();
        CargarComboUsuarios();
    }//GEN-LAST:event_jBnuevoUsuActionPerformed

    private void jBnuevaUbicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevaUbicActionPerformed
        // TODO add your handling code here:
        AltaLugar al = new AltaLugar();
        EscritorioMenu.add(al);
        al.show();

    }//GEN-LAST:event_jBnuevaUbicActionPerformed

    private void jBFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarActionPerformed
        // TODO add your handling code here:
        this.dis.setArchivo(f);
        IC.addDispositivo(dis);
        
    }//GEN-LAST:event_jBFinalizarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBActualizarUbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarUbiActionPerformed
        // TODO add your handling code here:
        this.jCBUbicacion.removeAllItems();
        CargarComboLugar();
    }//GEN-LAST:event_jBActualizarUbiActionPerformed

    private void jBActualizarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarUsuActionPerformed
        // TODO add your handling code here:
        this.jCBUsuario.removeAllItems();
        CargarComboUsuarios();
    }//GEN-LAST:event_jBActualizarUsuActionPerformed

    private void jBExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExaminarActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        this.f = fc.getSelectedFile();
        //Examinar ex= new Examinar();
    }//GEN-LAST:event_jBExaminarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizarUbi;
    private javax.swing.JButton jBActualizarUsu;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBExaminar;
    private javax.swing.JButton jBFinalizar;
    private javax.swing.JButton jBnuevaUbic;
    private javax.swing.JButton jBnuevoUsu;
    private javax.swing.JComboBox jCBUbicacion;
    private javax.swing.JComboBox jCBUsuario;
    private javax.swing.JLabel jLIP;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLXML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTIP;
    private javax.swing.JTextPane jTObserva;
    // End of variables declaration//GEN-END:variables

public void controlOcultos(){
    if(!cate.getNombrePadre().equals("Computadora")){
        this.jBExaminar.setEnabled(false);
        this.jTIP.setEnabled(false);
        this.jLIP.setEnabled(false);
        this.jLXML.setEnabled(false);
    }
    if(!cate.getNombrePadre().equals("Computadora") && !cate.getNombrePadre().equals("Impresora") && !cate.getNombrePadre().equals("Scanner")){
        this.jCBUsuario.setEnabled(false);
        this.jBnuevoUsu.setEnabled(false);
        this.jLUsuario.setEnabled(false);
    }
}
public void CargarComboUsuarios(){
    ArrayList usuarios; 
    usuarios=IC.listarUsuarios();
    Iterator it = usuarios.iterator();
    while(it.hasNext()){
        Usuario u = (Usuario) it.next();
        this.jCBUsuario.addItem(u.getNombre()+" "+u.getApellido());
    }
}
public void CargarComboLugar(){
    ArrayList lugares; 
    lugares=IC.listarLugares();
    Iterator it = lugares.iterator();
    while(it.hasNext()){
        Lugar l = (Lugar) it.next();
        this.jCBUbicacion.addItem(l.getLocal()+"->"+l.getSeccion());
    }


}


}