/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Clases.Categoria;
import Clases.Dispositivo;
import static Swing.Console.EscritorioMenu;
import java.awt.Dimension;

/**
 *
 * @author Joaquin
 */
public class AltaEquipo extends javax.swing.JInternalFrame {

    /**
     * Creates new form AltaEquipo
     */
    public AltaEquipo(Categoria cat) {
        initComponents();
        this.cate=cat;
        this.jTCategoria.setText(cate.getNombrePadre()+"-->"+cate.getNombre());
        controlOcultos();
        

        
    }
    private Categoria cate;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel15 = new javax.swing.JLabel();
        jTFactura3 = new javax.swing.JTextField();
        jBCancelar = new javax.swing.JButton();
        jBAtras = new javax.swing.JButton();
        jBSiguiente = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTId = new javax.swing.JTextField();
        jTCategoria = new javax.swing.JTextField();
        jTMarca = new javax.swing.JTextField();
        jTModelo = new javax.swing.JTextField();
        jTProveedor = new javax.swing.JTextField();
        JTGarantia = new javax.swing.JTextField();
        jTFactura = new javax.swing.JTextField();
        jFTFecha = new javax.swing.JFormattedTextField();
        jCBEstado = new javax.swing.JComboBox();
        jLproc = new javax.swing.JLabel();
        jTProc = new javax.swing.JTextField();
        jLMem = new javax.swing.JLabel();
        jTMem = new javax.swing.JTextField();
        jLHDD = new javax.swing.JLabel();
        jTHDD = new javax.swing.JTextField();

        jLabel15.setText("Factura:");

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Nuevo Equipo");
        setAutoscrolls(true);

        jBCancelar.setText("Cancelar");

        jBAtras.setText("<- Atras");

        jBSiguiente.setText("Siguiente->");
        jBSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSiguienteActionPerformed(evt);
            }
        });

        jLabel1.setText("Id de Equipo:");

        jLabel2.setText("Categoría:");

        jLabel3.setText("Marca:");

        jLabel4.setText("Modelo:");

        jLabel8.setText("Fecha de compra:");

        jLabel9.setText("Proveedor:");

        jLabel10.setText("Estado:");

        jLabel11.setText("Garantía:");

        jLabel12.setText("Factura:");

        jTId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTIdActionPerformed(evt);
            }
        });

        jTCategoria.setEditable(false);
        jTCategoria.setEnabled(false);

        jFTFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        jLproc.setText("Procesador:");

        jLMem.setText("Memoria:");

        jLHDD.setText("HDD:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTCategoria)
                            .addComponent(jTModelo)
                            .addComponent(jTMarca)
                            .addComponent(jTId)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jBAtras)
                            .addComponent(jLproc, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLMem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLHDD, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTProc)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jBCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jBSiguiente))
                            .addComponent(jTProveedor)
                            .addComponent(JTGarantia)
                            .addComponent(jTFactura)
                            .addComponent(jFTFecha)
                            .addComponent(jCBEstado, 0, 230, Short.MAX_VALUE)
                            .addComponent(jTMem, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTHDD, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jFTFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jCBEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(JTGarantia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLproc)
                    .addComponent(jTProc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLMem)
                    .addComponent(jTMem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTHDD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLHDD))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCancelar)
                    .addComponent(jBAtras)
                    .addComponent(jBSiguiente))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void jTIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTIdActionPerformed

    private void jBSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSiguienteActionPerformed
        // TODO add your handling code here:
        
        Dispositivo disp = new Dispositivo();
        disp.setIdDisp(Integer.parseInt(this.jTId.getText()));
        disp.setTipo(cate);
        disp.setMarca(this.jTMarca.getText());
        disp.setModelo(this.jTModelo.getText());
        disp.setProveedor(this.jTProveedor.getText());
        disp.setFactura(Integer.parseInt(this.jTFactura.getText()));
        disp.setGarantia(Integer.parseInt(this.JTGarantia.getText()));
        if(cate.getNombrePadre().equals("Computadora")){
            disp.setProcesador(this.jTProc.getText());
            disp.setMemoria(this.jTMem.getText());
            disp.setHDD(this.jTHDD.getText());
        }
         
        AltaEquipo2 ae = new AltaEquipo2(disp);
        EscritorioMenu.add(ae);
        ae.show();
        this.dispose();
    }//GEN-LAST:event_jBSiguienteActionPerformed
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTGarantia;
    private javax.swing.JButton jBAtras;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBSiguiente;
    private javax.swing.JComboBox jCBEstado;
    private javax.swing.JFormattedTextField jFTFecha;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLHDD;
    private javax.swing.JLabel jLMem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLproc;
    private javax.swing.JTextField jTCategoria;
    private javax.swing.JTextField jTFactura;
    private javax.swing.JTextField jTFactura3;
    private javax.swing.JTextField jTHDD;
    private javax.swing.JTextField jTId;
    private javax.swing.JTextField jTMarca;
    private javax.swing.JTextField jTMem;
    private javax.swing.JTextField jTModelo;
    private javax.swing.JTextField jTProc;
    private javax.swing.JTextField jTProveedor;
    // End of variables declaration//GEN-END:variables

public void controlOcultos(){
    if(!cate.getNombrePadre().equals("Computadora")){
        this.jTHDD.setEnabled(false);
        this.jLHDD.setEnabled(false);
        this.jLMem.setEnabled(false);
        this.jTMem.setEnabled(false);
        this.jLproc.setEnabled(false);
        this.jTProc.setEnabled(false);
    }
}

}




