/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Clases.Categoria;
import Clases.Dispositivo;
import Clases.Lugar;
import Clases.Usuario;
import Controladores.Fabrica;
import Controladores.IControlador;
import static Swing.Console.EscritorioMenu;
import java.awt.event.ItemEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.nio.file.CopyOption;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.StringTokenizer;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Nelson
 */
public class AltaEquipo2 extends javax.swing.JInternalFrame {
    private Categoria cate;
    private IControlador IC; 
    private String ruta;
    private Dispositivo dis;
    private String us;
    private String lug;
    private String RutaFinal;
    
    /**
     * Creates new form AltaEquipo2
     */
    public AltaEquipo2(Dispositivo disp) {
        initComponents();
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        IC = fabrica.getICtrl();
        this.cate=disp.getTipo();
        this.dis=disp;
        controlOcultos();
        CargarComboLugar();
        CargarComboUsuarios();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jBnuevoUsu = new javax.swing.JButton();
        jBnuevaUbic = new javax.swing.JButton();
        jCBUsuario = new javax.swing.JComboBox();
        jCBUbicacion = new javax.swing.JComboBox();
        jLUsuario = new javax.swing.JLabel();
        jTIP = new javax.swing.JTextField();
        jLIP = new javax.swing.JLabel();
        jLArchivo = new javax.swing.JLabel();
        jBExaminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTObserva = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jBFinalizar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();
        jBActualizarUsu = new javax.swing.JButton();
        jBActualizarUbi = new javax.swing.JButton();
        jTArchivo = new javax.swing.JTextField();

        setClosable(true);

        jLabel6.setText("Ubicación:");

        jBnuevoUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevoU.png"))); // NOI18N
        jBnuevoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoUsuActionPerformed(evt);
            }
        });

        jBnuevaUbic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ubicacion.png"))); // NOI18N
        jBnuevaUbic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevaUbicActionPerformed(evt);
            }
        });

        jCBUsuario.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBUsuarioItemStateChanged(evt);
            }
        });

        jCBUbicacion.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCBUbicacionItemStateChanged(evt);
            }
        });

        jLUsuario.setText("Usuario:");

        jLIP.setText("IP:");

        jLArchivo.setText("Archivo:");

        jBExaminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/buscar .png"))); // NOI18N
        jBExaminar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBExaminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExaminarActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(jTObserva);

        jLabel1.setText("Comentario:");

        jBFinalizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finalizar.png"))); // NOI18N
        jBFinalizar.setText("Finalizar");
        jBFinalizar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarActionPerformed(evt);
            }
        });

        jBCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        jBActualizarUsu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        jBActualizarUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarUsuActionPerformed(evt);
            }
        });

        jBActualizarUbi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        jBActualizarUbi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarUbiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBFinalizar)
                .addGap(21, 21, 21))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLArchivo)
                            .addComponent(jLUsuario)
                            .addComponent(jLabel6)
                            .addComponent(jLIP))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jTIP)
                                        .addGap(33, 33, 33))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jCBUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jBActualizarUbi, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                            .addComponent(jCBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jBActualizarUsu, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBnuevoUsu)
                                    .addComponent(jBnuevaUbic)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jTArchivo)
                                .addGap(34, 34, 34)
                                .addComponent(jBExaminar))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBnuevoUsu)
                    .addComponent(jBActualizarUsu)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLUsuario)
                        .addComponent(jCBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBnuevaUbic)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(jCBUbicacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBActualizarUbi)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIP)
                    .addComponent(jTIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLArchivo)
                        .addComponent(jBExaminar))
                    .addComponent(jTArchivo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBFinalizar)
                    .addComponent(jBCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnuevoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoUsuActionPerformed
        // TODO add your handling code here:
        AltaUsuario au = new AltaUsuario();
        EscritorioMenu.add(au);
        au.show();
        this.jCBUsuario.removeAllItems();
        CargarComboUsuarios();
    }//GEN-LAST:event_jBnuevoUsuActionPerformed

    private void jBnuevaUbicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevaUbicActionPerformed
        // TODO add your handling code here:
        AltaLugar al = new AltaLugar();
        EscritorioMenu.add(al);
        al.show();
        this.jCBUbicacion.removeAllItems();
        CargarComboLugar();

    }//GEN-LAST:event_jBnuevaUbicActionPerformed

    private void jBFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarActionPerformed
        // TODO add your handling code here:
        StringTokenizer tokens = new StringTokenizer(us);
        Usuario u = new Usuario(Integer.parseInt(tokens.nextToken()),tokens.nextToken(),tokens.nextToken());
        this.dis.setUsuario(u);
        StringTokenizer tokens1 = new StringTokenizer(lug);
        Lugar l = new Lugar(Integer.parseInt(tokens1.nextToken()),tokens1.nextToken(),tokens1.nextToken());
        this.dis.setLugar(l);
//        if(this.dis.getTipo().getNombrePadre().equals("Computadora")){
//            this.dis.setArchivo(f);
//        }
        this.dis.setIp(this.jTIP.getText());
        this.dis.setNota(this.jTObserva.getText());
        this.dis.setRuta(this.RutaFinal);
        
        
        IC.addDispositivo(dis);
        RutaFinal="";
        JOptionPane.showMessageDialog(null, "!El equipo  "+dis.getIdDisp()+" fue agregado!","EXITO",JOptionPane.INFORMATION_MESSAGE);
        
    }//GEN-LAST:event_jBFinalizarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarActionPerformed

    private void jBActualizarUbiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarUbiActionPerformed
        // TODO add your handling code here:
        this.jCBUbicacion.removeAllItems();
        CargarComboLugar();
    }//GEN-LAST:event_jBActualizarUbiActionPerformed

    private void jBActualizarUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarUsuActionPerformed
        // TODO add your handling code here:
        this.jCBUsuario.removeAllItems();
        CargarComboUsuarios();
    }//GEN-LAST:event_jBActualizarUsuActionPerformed

    private void jBExaminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExaminarActionPerformed
        // TODO add your handling code here:
        crearCarpeta();
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        this.ruta = fc.getSelectedFile().getAbsolutePath();
        StringTokenizer tokens = new StringTokenizer(ruta);
        tokens.nextToken(".");
        String extension= (tokens.nextToken("."));
        try{
            this.RutaFinal = "\\\\192.168.1.107\\equipos\\"+Integer.toString(dis.getIdDisp())+"\\"+Integer.toString(dis.getIdDisp())+"."+extension;
            copy(ruta,this.RutaFinal);
            
        }
        catch(Exception ex){           
        }
        //String ruta = fc.getSelectedFile().getAbsolutePath();
        //Examinar ex= new Examinar();
    }//GEN-LAST:event_jBExaminarActionPerformed

    private void jCBUsuarioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBUsuarioItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED)
            this.us=(evt.getItem().toString());
    }//GEN-LAST:event_jCBUsuarioItemStateChanged

    private void jCBUbicacionItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCBUbicacionItemStateChanged
        // TODO add your handling code here:
        if(evt.getStateChange()==ItemEvent.SELECTED)
            this.lug=(evt.getItem().toString());
    }//GEN-LAST:event_jCBUbicacionItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBActualizarUbi;
    private javax.swing.JButton jBActualizarUsu;
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBExaminar;
    private javax.swing.JButton jBFinalizar;
    private javax.swing.JButton jBnuevaUbic;
    private javax.swing.JButton jBnuevoUsu;
    private javax.swing.JComboBox jCBUbicacion;
    private javax.swing.JComboBox jCBUsuario;
    private javax.swing.JLabel jLArchivo;
    private javax.swing.JLabel jLIP;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTArchivo;
    private javax.swing.JTextField jTIP;
    private javax.swing.JTextPane jTObserva;
    // End of variables declaration//GEN-END:variables

public void controlOcultos(){
    if(!cate.getNombrePadre().equals("Computadora") && !cate.getNombrePadre().equals("computadora")){
        this.jBExaminar.setEnabled(false);
        this.jTIP.setEnabled(false);
        this.jLIP.setEnabled(false);
        this.jLArchivo.setEnabled(false);
    }
    if(!cate.getNombrePadre().equals("Computadora") && !cate.getNombrePadre().equals("computadora") && !cate.getNombrePadre().equals("Impresora") && !cate.getNombrePadre().equals("Scanner")){
        this.jCBUsuario.setEnabled(false);
        this.jBnuevoUsu.setEnabled(false);
        this.jLUsuario.setEnabled(false);
    }
}
public void CargarComboUsuarios(){
    ArrayList usuarios; 
    usuarios=IC.listarUsuarios();
    Iterator it = usuarios.iterator();
    while(it.hasNext()){
        Usuario u = (Usuario) it.next();
        this.jCBUsuario.addItem(u.getId()+" "+u.getNombre()+" "+u.getApellido());
    }
}
public void CargarComboLugar(){
    ArrayList lugares; 
    lugares=IC.listarLugares();
    Iterator it = lugares.iterator();
    while(it.hasNext()){
        Lugar l = (Lugar) it.next();
        this.jCBUbicacion.addItem(l.getId()+" "+l.getLocal()+" "+l.getSeccion());
    }


}
public void escribir(String nombreArchivo){

    File f;
    f = new File("nombreArchivo");
    try{
        FileWriter w = new FileWriter(f);
        BufferedWriter bw = new BufferedWriter(w);
        PrintWriter wr = new PrintWriter(bw);  
        wr.write("Esta es una linea de codigo");//escribimos en el archivo
        wr.append(" - y aqui continua"); //concatenamos en el archivo sin borrar lo existente
                //ahora cerramos los flujos de canales de datos, al cerrarlos el archivo quedará guardado con información escrita
                //de no hacerlo no se escribirá nada en el archivo
        wr.close();
        bw.close();
    }catch(IOException e){};
}

public static void copy(String origen, String destino) throws IOException {
        Path FROM = Paths.get(origen);
        Path TO = Paths.get(destino);
        //sobreescribir el fichero de destino, si existe, y copiar
        // los atributos, incluyendo los permisos rwx
        CopyOption[] options = new CopyOption[]{
          StandardCopyOption.REPLACE_EXISTING,
          StandardCopyOption.COPY_ATTRIBUTES
        }; 
        Files.copy(FROM, TO, options);
    }
public void testbat() {
	
	Runtime aplicacion = Runtime.getRuntime(); 
        try{
            
//            aplicacion.getRuntime().exec(new String[]{"cmd.exe","/c","start"});
//            aplicacion.getRuntime().exec("md \\192.168.1.107\\equipos\\"+Integer.toString(dis.getIdDisp()));
        }
            //aplicacion.exec("cmd.exe /K C:\fichero.bat"); }
        catch(Exception e){ 
            System.out.println(e);}

	}
public void crearCarpeta(){
    File folder = new File("\\\\192.168.1.107\\equipos\\"+Integer.toString(dis.getIdDisp()));
    folder.mkdir();
}


}