/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Clases.Software;
import Controladores.Fabrica;
import Controladores.IControlador;
import static Swing.Console.EscritorioMenu;
import java.awt.event.ItemEvent;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author Joaquin
 */
public class AltaSoftware extends javax.swing.JInternalFrame{
    private IControlador IC;
    private String tipo;
    private int equipo;
    private int id;

    /**
     * Creates new form Registrar
     */
    public AltaSoftware() {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        IC = fabrica.getICtrl();

        cargarCBbox();
    }
public AltaSoftware(int id) {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        IC = fabrica.getICtrl();
        cargarCBbox();
        this.jTextIDEquipo.setText(Integer.toString(id));
        this.jTextIDEquipo.setEnabled(false);
        this.id=id;
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jcbTipo = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtextID = new javax.swing.JTextField();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextKey = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextDesc = new javax.swing.JTextPane();
        jLabel6 = new javax.swing.JLabel();
        jTextLicencias = new javax.swing.JTextField();
        jBVerEquipo = new javax.swing.JButton();
        jTextIDEquipo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("Nuevo Software");

        jcbTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jcbTipoItemStateChanged(evt);
            }
        });

        jLabel1.setText("Tipo de Software:");

        jLabel3.setText("ID Software:");

        jtextID.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jtextIDFocusLost(evt);
            }
        });
        jtextID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtextIDActionPerformed(evt);
            }
        });

        jbAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/finalizar.png"))); // NOI18N
        jbAceptar.setText("Aceptar");
        jbAceptar.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jbAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAceptarActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");

        jLabel4.setText("Descripcion:");

        jLabel5.setText("CD Key:");

        jScrollPane1.setViewportView(jTextDesc);

        jLabel6.setText("Cantidad de licencias:");

        jTextLicencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextLicenciasActionPerformed(evt);
            }
        });

        jBVerEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ver.jpg"))); // NOI18N
        jBVerEquipo.setText("Ver");
        jBVerEquipo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jBVerEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVerEquipoActionPerformed(evt);
            }
        });

        jLabel2.setText("ID Equipo:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jbCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jbAceptar)
                        .addGap(41, 41, 41))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jtextID)
                            .addComponent(jcbTipo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(jTextKey, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextIDEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jBVerEquipo)))
                        .addContainerGap(18, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jTextLicencias, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextLicencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVerEquipo)
                    .addComponent(jTextIDEquipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbAceptar)
                    .addComponent(jbCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void cargarCBbox(){
        String str1="Sistema Operativo";
        String str2="Suite de Ofimatica";
        jcbTipo.addItem(str1);
        jcbTipo.addItem(str2);
        
//        ArrayList equipos; 
//        equipos=IC.listarEquipos();
//        Iterator it = equipos.iterator();
//        while(it.hasNext()){
//            int eq = (int) it.next();
//            jcbEquipo.addItem(eq);
//        }
    }
    private void jtextIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtextIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtextIDActionPerformed

    private void jcbTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jcbTipoItemStateChanged
        if(evt.getStateChange()==ItemEvent.SELECTED)
            this.tipo=(evt.getItem().toString());
    }//GEN-LAST:event_jcbTipoItemStateChanged

    private void jbAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAceptarActionPerformed
        if (this.jtextID.getText().isEmpty())
            JOptionPane.showMessageDialog(null, "Ingrese ID de Software","ERROR",JOptionPane.ERROR_MESSAGE);
        else
            if(this.jTextKey.getText().isEmpty())
                JOptionPane.showMessageDialog(null, "Ingrese el CD Key","ERROR",JOptionPane.ERROR_MESSAGE);
                    else{    
                        if(this.jTextIDEquipo.getText().isEmpty() || !IC.validarEquipo(Integer.parseInt(this.jTextIDEquipo.getText()))){
                            JOptionPane.showMessageDialog(null, "El equipo no existe o no es una computadora","ERROR",JOptionPane.ERROR_MESSAGE);
                        }
                        else{
                            if(IC.validarSW(Integer.parseInt(this.jtextID.getText()))){
                                IC.addSw(Integer.parseInt(this.jtextID.getText()), tipo, this.jTextDesc.getText(), this.jTextKey.getText(), Integer.parseInt(this.jTextLicencias.getText()));
                                IC.asociarEquipoSw(Integer.parseInt(this.jTextIDEquipo.getText()), Integer.parseInt(this.jtextID.getText()));
                                JOptionPane.showMessageDialog(null, "Ingresado con Exito","EXITO",JOptionPane.INFORMATION_MESSAGE);
                                dispose();
                            }
                            else
                                JOptionPane.showMessageDialog(null, "El id de Software ya existe","ERROR",JOptionPane.ERROR_MESSAGE);                                                   
                        }
                    }                    
    }//GEN-LAST:event_jbAceptarActionPerformed

    private void jTextLicenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextLicenciasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextLicenciasActionPerformed

    private void jBVerEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVerEquipoActionPerformed
        // TODO add your handling code here:
        if(IC.findDispositivo(Integer.parseInt(this.jTextIDEquipo.getText()))==null){
            JOptionPane.showMessageDialog(null, "El equipo no existe","ERROR",JOptionPane.ERROR_MESSAGE);
        }
        else{
            VerEditarEquipo vee = new VerEditarEquipo(Integer.parseInt(this.jTextIDEquipo.getText()),false);
            EscritorioMenu.add(vee);
            vee.show();
        }
    }//GEN-LAST:event_jBVerEquipoActionPerformed

    private void jtextIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtextIDFocusLost
        if(!this.jtextID.getText().isEmpty()){
            Software s = IC.findSw(Integer.parseInt(this.jtextID.getText()));
            if(!(s==null)){
                this.jcbTipo.setSelectedItem(s.getTipo());
                this.jTextLicencias.setText(Integer.toString(s.getCantLicencias()));
                this.jTextKey.setText(s.getCdKey());
                this.jTextDesc.setText(s.getDescripcion());
            }
        } 
        
    }//GEN-LAST:event_jtextIDFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBVerEquipo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextDesc;
    private javax.swing.JTextField jTextIDEquipo;
    private javax.swing.JTextField jTextKey;
    private javax.swing.JTextField jTextLicencias;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JComboBox jcbTipo;
    private javax.swing.JTextField jtextID;
    // End of variables declaration//GEN-END:variables
}
