/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Clases.Categoria;
import Clases.Dispositivo;
import static Swing.Console.EscritorioMenu;

/**
 *
 * @author Nelson
 */
public class AltaEquipo2 extends javax.swing.JInternalFrame {
    private Categoria cate;
    /**
     * Creates new form AltaEquipo2
     */
    public AltaEquipo2(Dispositivo disp) {
        initComponents();
        this.cate=disp.getTipo();
        controlOcultos();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jBnuevoUsu = new javax.swing.JButton();
        jBnuevoLocal = new javax.swing.JButton();
        jBnuevaSecc = new javax.swing.JButton();
        jCBUsuario = new javax.swing.JComboBox();
        jCBLocal = new javax.swing.JComboBox();
        jCBSeccion = new javax.swing.JComboBox();
        jLUsuario = new javax.swing.JLabel();
        jTIP = new javax.swing.JTextField();
        jLIP = new javax.swing.JLabel();
        jLXML = new javax.swing.JLabel();
        jBExaminar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTObserva = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        jBFinalizar = new javax.swing.JButton();
        jBCancelar = new javax.swing.JButton();

        setClosable(true);

        jLabel6.setText("Local:");

        jLabel7.setText("Sección:");

        jBnuevoUsu.setText("Nuevo");
        jBnuevoUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoUsuActionPerformed(evt);
            }
        });

        jBnuevoLocal.setText("Nuevo");
        jBnuevoLocal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevoLocalActionPerformed(evt);
            }
        });

        jBnuevaSecc.setText("Nuevo");
        jBnuevaSecc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBnuevaSeccActionPerformed(evt);
            }
        });

        jCBSeccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBSeccionActionPerformed(evt);
            }
        });

        jLUsuario.setText("Usuario:");

        jLIP.setText("IP:");

        jLXML.setText("Adjuntar XML");

        jBExaminar.setText("Examinar");

        jScrollPane1.setViewportView(jTObserva);

        jLabel1.setText(" Observación:");

        jBFinalizar.setText("Finalizar");
        jBFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBFinalizarActionPerformed(evt);
            }
        });

        jBCancelar.setText("Cancelar");
        jBCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLUsuario)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jCBUsuario, 0, 249, Short.MAX_VALUE)
                            .addComponent(jCBLocal, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jBnuevoLocal))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jBnuevoUsu))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(jLIP))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTIP)
                                    .addComponent(jCBSeccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 246, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jBnuevaSecc)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLXML)
                .addGap(18, 18, 18)
                .addComponent(jBExaminar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jBCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBFinalizar)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLUsuario)
                    .addComponent(jCBUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnuevoUsu))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jCBLocal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnuevoLocal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jCBSeccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBnuevaSecc))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLIP)
                    .addComponent(jTIP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLXML)
                    .addComponent(jBExaminar))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBFinalizar)
                    .addComponent(jBCancelar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBnuevoUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoUsuActionPerformed
        // TODO add your handling code here:
        AltaUsuario au = new AltaUsuario();
        EscritorioMenu.add(au);
        au.show();
    }//GEN-LAST:event_jBnuevoUsuActionPerformed

    private void jBnuevoLocalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevoLocalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnuevoLocalActionPerformed

    private void jBnuevaSeccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBnuevaSeccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBnuevaSeccActionPerformed

    private void jCBSeccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBSeccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCBSeccionActionPerformed

    private void jBFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBFinalizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBFinalizarActionPerformed

    private void jBCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCancelarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBCancelarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBCancelar;
    private javax.swing.JButton jBExaminar;
    private javax.swing.JButton jBFinalizar;
    private javax.swing.JButton jBnuevaSecc;
    private javax.swing.JButton jBnuevoLocal;
    private javax.swing.JButton jBnuevoUsu;
    private javax.swing.JComboBox jCBLocal;
    private javax.swing.JComboBox jCBSeccion;
    private javax.swing.JComboBox jCBUsuario;
    private javax.swing.JLabel jLIP;
    private javax.swing.JLabel jLUsuario;
    private javax.swing.JLabel jLXML;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTIP;
    private javax.swing.JTextPane jTObserva;
    // End of variables declaration//GEN-END:variables

public void controlOcultos(){
    if(!cate.getNombrePadre().equals("Computadora")){
        this.jBExaminar.setEnabled(false);
        this.jTIP.setEnabled(false);
        this.jLIP.setEnabled(false);
        this.jLXML.setEnabled(false);
    }
    if(!cate.getNombrePadre().equals("Computadora") && !cate.getNombrePadre().equals("Impresora") && !cate.getNombrePadre().equals("Scanner")){
        this.jCBUsuario.setEnabled(false);
        this.jBnuevoUsu.setEnabled(false);
        this.jLUsuario.setEnabled(false);
    
    }



}
}