/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

//import lab01.Interfaces.RegUsuario;




/**
 *
 * @author Joaquin
 */
public class Console extends javax.swing.JFrame {

    /**
     * Creates new form Console
     */
    public Console() {
        initComponents();
        login log = new login();
        EscritorioMenu.add(log);
        log.show();

       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        EscritorioMenu = new javax.swing.JDesktopPane();
        menu = new javax.swing.JMenuBar();
        smnuSalir = new javax.swing.JMenu();
        jmAltaUsuario = new javax.swing.JMenuItem();
        jmAltaLugar = new javax.swing.JMenuItem();
        jmAltaSoftware = new javax.swing.JMenuItem();
        jmEquipo = new javax.swing.JMenuItem();
        jMSalir = new javax.swing.JMenuItem();
        ver = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuVerUsuarios = new javax.swing.JMenuItem();
        jMenuVerSoftware = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        smnuSalir.setText("Nuevo");

        jmAltaUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/nuevoU.png"))); // NOI18N
        jmAltaUsuario.setText("Usuario");
        jmAltaUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAltaUsuarioActionPerformed(evt);
            }
        });
        smnuSalir.add(jmAltaUsuario);

        jmAltaLugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/ubicacion.png"))); // NOI18N
        jmAltaLugar.setText("Lugar");
        jmAltaLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAltaLugarActionPerformed(evt);
            }
        });
        smnuSalir.add(jmAltaLugar);

        jmAltaSoftware.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/software.png"))); // NOI18N
        jmAltaSoftware.setText("Software");
        jmAltaSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAltaSoftwareActionPerformed(evt);
            }
        });
        smnuSalir.add(jmAltaSoftware);

        jmEquipo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pc.png"))); // NOI18N
        jmEquipo.setText("Equipo");
        jmEquipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmEquipoActionPerformed(evt);
            }
        });
        smnuSalir.add(jmEquipo);

        jMSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        jMSalir.setText("Salir");
        jMSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMSalirActionPerformed(evt);
            }
        });
        smnuSalir.add(jMSalir);

        menu.add(smnuSalir);

        ver.setText("Ver");
        ver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verActionPerformed(evt);
            }
        });

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pc.png"))); // NOI18N
        jMenuItem4.setText("Equipos");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        ver.add(jMenuItem4);

        jMenuVerUsuarios.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/user.png"))); // NOI18N
        jMenuVerUsuarios.setText("Usuarios");
        jMenuVerUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVerUsuariosActionPerformed(evt);
            }
        });
        ver.add(jMenuVerUsuarios);

        jMenuVerSoftware.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/software.png"))); // NOI18N
        jMenuVerSoftware.setText("Software");
        jMenuVerSoftware.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuVerSoftwareActionPerformed(evt);
            }
        });
        ver.add(jMenuVerSoftware);

        menu.add(ver);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EscritorioMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 1100, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(EscritorioMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAltaLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAltaLugarActionPerformed
        AltaLugar alta = new AltaLugar();
        EscritorioMenu.add(alta);
        alta.show();
        
    }//GEN-LAST:event_jmAltaLugarActionPerformed

    
    
    private void jmAltaUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAltaUsuarioActionPerformed
        AltaUsuario altaT = new AltaUsuario();
        EscritorioMenu.add(altaT);
        altaT.show();
        // TODO add your handling code here:
    }//GEN-LAST:event_jmAltaUsuarioActionPerformed

    private void jmAltaSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAltaSoftwareActionPerformed
        // TODO add your handling code here:
        AltaSoftware soft = new AltaSoftware();
        EscritorioMenu.add(soft);
        soft.show();
    }//GEN-LAST:event_jmAltaSoftwareActionPerformed

    private void jmEquipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmEquipoActionPerformed

        // TODO add your handling code here:
        SelCat sc = new SelCat();
        EscritorioMenu.add(sc);
        sc.show();
    }//GEN-LAST:event_jmEquipoActionPerformed

    private void jMSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMSalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMSalirActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        VerEquipos ve = new VerEquipos();
        EscritorioMenu.add(ve);
        ve.show();
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuVerUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVerUsuariosActionPerformed
        // TODO add your handling code here:
        VerUsuarios vu = new VerUsuarios();
        EscritorioMenu.add(vu);
        vu.show();
    }//GEN-LAST:event_jMenuVerUsuariosActionPerformed

    private void jMenuVerSoftwareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuVerSoftwareActionPerformed
        // TODO add your handling code here:
        ListarSoftware ls = new ListarSoftware();
        EscritorioMenu.add(ls);
        ls.show();
    }//GEN-LAST:event_jMenuVerSoftwareActionPerformed

    private void verActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Console.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Console.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Console.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Console.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Console().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane EscritorioMenu;
    private javax.swing.JMenuItem jMSalir;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuVerSoftware;
    private javax.swing.JMenuItem jMenuVerUsuarios;
    private javax.swing.JMenuItem jmAltaLugar;
    private javax.swing.JMenuItem jmAltaSoftware;
    private javax.swing.JMenuItem jmAltaUsuario;
    private javax.swing.JMenuItem jmEquipo;
    private javax.swing.JMenuBar menu;
    private javax.swing.JMenu smnuSalir;
    private javax.swing.JMenu ver;
    // End of variables declaration//GEN-END:variables
}
