/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Clases.Categoria;
import Controladores.Fabrica;
import Controladores.IControlador;
import static Swing.Console.EscritorioMenu;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Joaquin
 */
public class SelCat extends javax.swing.JInternalFrame {
    private IControlador IC;
    private Categoria cat;
    boolean valido=true;

    /**
     * Creates new form SelCat
     */
    public SelCat() {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        IC = fabrica.getICtrl();
        modelCat= new DefaultListModel();
        Raiz = new DefaultMutableTreeNode("Categorias");
        modelo = new DefaultTreeModel(Raiz);
        JTree tree = new JTree(modelo);       
        cargarArbol();
        this.jLSelCat.setVisible(false);
        
        
    }
    DefaultListModel modelCat;
    DefaultMutableTreeNode Raiz;// = new DefaultMutableTreeNode("Restaurantes");
    DefaultTreeModel modelo; //= new DefaultTreeModel(Raiz);
    
    public void cargarArbol(){
        this.jTCategoria.removeAll();
            ArrayList cats = IC.ListarCat();
            Iterator it = cats.iterator();
            
            while(it.hasNext()){
                Iterator it1 = cats.iterator();
                Categoria cat = (Categoria)it.next();
                if (cat.getNombrePadre().equals("Categorias")){ 
                    DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(cat.getNombre());
                    modelo.insertNodeInto(nodo, Raiz, 0);
                    while(it1.hasNext()){
                        Categoria cat1 = (Categoria)it1.next();
                        if((!(cat1.getNombrePadre().equals("Categorias"))) && (cat1.getNombrePadre().equals(cat.getNombre()))){
                            DefaultMutableTreeNode nodo1 = new DefaultMutableTreeNode(cat1.getNombre());
                            modelo.insertNodeInto(nodo1, nodo, 0);
                        }
                    }          
                }
            }  
            this.jTCategoria.setModel(modelo);
        }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCategoria = new javax.swing.JTree();
        jbSiguiente = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLSelCat = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jBCategoria = new javax.swing.JButton();
        jBActualizar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Seleccionar Categoria");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTCategoria.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTCategoria.addTreeSelectionListener(new javax.swing.event.TreeSelectionListener() {
            public void valueChanged(javax.swing.event.TreeSelectionEvent evt) {
                jTCategoriaValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTCategoria);

        jbSiguiente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/siguiente.png"))); // NOI18N
        jbSiguiente.setText("Siguiente");
        jbSiguiente.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jbSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSiguienteActionPerformed(evt);
            }
        });

        jbCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cancelar.png"))); // NOI18N
        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Seleccione una categoría:");

        jLSelCat.setForeground(new java.awt.Color(255, 0, 0));
        jLSelCat.setText("Debe seleccionar una categoría");

        jLabel2.setText("Nueva Categoria:");

        jBCategoria.setText("jButton1");
        jBCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCategoriaActionPerformed(evt);
            }
        });

        jBActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/actualizar.png"))); // NOI18N
        jBActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBActualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jbCancelar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jbSiguiente))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(jLabel1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLSelCat)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(46, 46, 46)
                                        .addComponent(jBCategoria))
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBActualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jBActualizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLSelCat)
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jBCategoria))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbSiguiente)
                    .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jbSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSiguienteActionPerformed
        // TODO add your handling code here:
        if(this.cat == null || this.cat.getNombre()==null){
            this.jLSelCat.setText("Debe seleccionar una categoría");
                this.jLSelCat.setVisible(true);
        }
        else{
            int idCat = IC.retornoIdCategoria(cat);
            cat.setId(idCat);
            AltaEquipo ae = new AltaEquipo(this.cat);
            Console.EscritorioMenu.add(ae);
            ae.show();
            this.dispose();
        } 
    }//GEN-LAST:event_jbSiguienteActionPerformed

    private void jTCategoriaValueChanged(javax.swing.event.TreeSelectionEvent evt) {//GEN-FIRST:event_jTCategoriaValueChanged
        // TODO add your handling code here:
        DefaultMutableTreeNode sel = (DefaultMutableTreeNode)this.jTCategoria.getLastSelectedPathComponent();
        this.cat = new Categoria((String)sel.getUserObject(),null);
        if(!sel.isRoot()){
            DefaultMutableTreeNode padre = (DefaultMutableTreeNode) sel.getParent(); 
            this.cat.setNombrePadre((String)padre.getUserObject());
            if(padre.getUserObject().equals("Categorias")){
                this.jLSelCat.setText("Seleccione una categoria del 2do nivel");
                this.jLSelCat.setVisible(true);
            }
            else
                this.jLSelCat.setVisible(false);
        }
        else{
            this.jLSelCat.setText("Seleccione una categoria del 2do nivel");
            this.jLSelCat.setVisible(true);
        }
    }//GEN-LAST:event_jTCategoriaValueChanged

    private void jBCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCategoriaActionPerformed
        // TODO add your handling code here:
        NuevaCategoria nc = new NuevaCategoria();
        EscritorioMenu.add(nc);
        nc.show();
        
    }//GEN-LAST:event_jBCategoriaActionPerformed

    private void jBActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBActualizarActionPerformed
        // TODO add your handling code here:
        
        //this.jTCategoria.removeAll();
        this.Raiz.removeAllChildren();
        modelo.reload();
        cargarArbol();
        
    }//GEN-LAST:event_jBActualizarActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBActualizar;
    private javax.swing.JButton jBCategoria;
    private javax.swing.JLabel jLSelCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTCategoria;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbSiguiente;
    // End of variables declaration//GEN-END:variables
    
}
