/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Swing;

import Clases.Categoria;
import Controladores.Fabrica;
import Controladores.IControlador;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.DefaultListModel;
import javax.swing.JTree;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Joaquin
 */
public class SelCat extends javax.swing.JInternalFrame {
    private IControlador IC;

    /**
     * Creates new form SelCat
     */
    public SelCat() {
        initComponents();
        Fabrica fabrica = Fabrica.getInstance();
        IC = fabrica.getICtrl();
        this.buttonGroup1.add(jRbCrear);
        this.buttonGroup1.add(jRbSeleccionar);
        modelCat= new DefaultListModel();
        Raiz = new DefaultMutableTreeNode("Categorias");
        modelo = new DefaultTreeModel(Raiz);
        JTree tree = new JTree(modelo);
        cargarArbol();
    }
    DefaultListModel modelCat;
    DefaultMutableTreeNode Raiz;// = new DefaultMutableTreeNode("Restaurantes");
    DefaultTreeModel modelo; //= new DefaultTreeModel(Raiz);
    
    public void cargarArbol(){
       
            ArrayList cats = IC.ListarCat();
            Iterator it = cats.iterator();
            
            while(it.hasNext()){
                Iterator it1 = cats.iterator();
                Categoria cat = (Categoria)it.next();
                if (cat.getNombrePadre()==null){ 
                    DefaultMutableTreeNode nodo = new DefaultMutableTreeNode(cat.getNombre());
                    modelo.insertNodeInto(nodo, Raiz, 0);
                    while(it1.hasNext()){
                        Categoria cat1 = (Categoria)it1.next();
                        if((!(cat1.getNombrePadre()==null)) && (cat1.getNombrePadre().equals(cat.getNombre()))){
                            DefaultMutableTreeNode nodo1 = new DefaultMutableTreeNode(cat1.getNombre());
                            modelo.insertNodeInto(nodo1, nodo, 0);
                        }
                    }          
                }
            }  
            this.jTCategoria.setModel(modelo);
        }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTCategoria = new javax.swing.JTree();
        jbAceptar = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jRbSeleccionar = new javax.swing.JRadioButton();
        jRbCrear = new javax.swing.JRadioButton();
        jTNCategoria = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Seleccionar Categoria");

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        jTCategoria.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jTCategoria.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTCategoria.setRootVisible(false);
        jScrollPane1.setViewportView(jTCategoria);

        jbAceptar.setText("Aceptar");

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jRbSeleccionar.setText("Seleccionar una categoria:");
        jRbSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRbSeleccionarActionPerformed(evt);
            }
        });

        jRbCrear.setText("Crear una categoria nueva:");

        jTNCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNCategoriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jbCancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbAceptar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTNCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRbCrear)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRbSeleccionar))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 5, Short.MAX_VALUE)
                .addComponent(jRbSeleccionar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jRbCrear)
                .addGap(18, 18, 18)
                .addComponent(jTNCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCancelar)
                    .addComponent(jbAceptar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed

    private void jRbSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRbSeleccionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRbSeleccionarActionPerformed

    private void jTNCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNCategoriaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNCategoriaActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton jRbCrear;
    private javax.swing.JRadioButton jRbSeleccionar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTCategoria;
    private javax.swing.JTextField jTNCategoria;
    private javax.swing.JButton jbAceptar;
    private javax.swing.JButton jbCancelar;
    // End of variables declaration//GEN-END:variables
    
}
